### ISSUE TITLE
sriov

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/network-charts-repackage#147]
sriov shema ， 没有 配置 物理网卡 pci 号的地方

**Comment by cyclinder** [comment]
指的是 sriov-device-plugin 发现主机PF的 配置？ 那部分我认为太复杂了，默认配置里面就包括比较常见、支持sriov功能系列的网卡了。如果有需求，可以部署上来后再编辑 其configMao

**Comment by cyclinder** [comment]
https://github.com/DaoCloud/network-charts-repackage/pull/188
