### ISSUE TITLE
【现象】安装插件ingress-nginx,报如图

### ISSUE THREAD

**Issue by yulng** [DaoCloud/network-charts-repackage#198]
![企业微信截图_0d66d479-8999-4cd1-aa59-d83fac039c7b](https://user-images.githubusercontent.com/31728060/192952354-421b6d61-58d3-409e-9c8c-f0c5c13917a5.png)
【配置】
weight=1
【解决】已确认需要修复

**Comment by lou-lan** [comment]
Fix in https://github.com/DaoCloud/network-charts-repackage/pull/180
