### ISSUE TITLE
镜像拉取目标错误

### ISSUE THREAD

**Issue by wzshiming** [DaoCloud/network-charts-repackage#260]
我在 docker.m.daocloud.io 的日志看到大量拉取 docker.m.daocloud.io/docker.m.daocloud.io:1.23.0-debian-11-r8 的日志,
根据 tag 找到实际要拉取的应该是 docker.m.daocloud.io/bitnami/envoy:1.23.0-debian-11-r8,

看起来这个的拉取策略是 先  `{{ .global.imageRegistry }}/{{ .registry }}` 再 `{{ .global.imageRegistry }}/{{ .repository }}` ?

https://github.com/DaoCloud/network-charts-repackage/blob/86110149e0ad6872a41ade14fa36ec4db716a213/charts/contour/contour/values.yaml#L21-L25

还有一个拉取 `docker.m.daocloud.io/9.1.6/docker.io:1.22.0-debian-11-r4` 的是不是哪里拼错了, 原目标应该是 `docker.m.daocloud.io/bitnami/contour:1.22.0-debian-11-r4`

https://github.com/DaoCloud/network-charts-repackage/blob/86110149e0ad6872a41ade14fa36ec4db716a213/charts/contour/contour/values.yaml#L7-L10

**Comment by lou-lan** [comment]
今天上午，安装器的 --set  repository 和 --set  registry 搞混了，下午应该就不会有这个日志了
