### ISSUE TITLE
nmstate install doc need to modify

### ISSUE THREAD

**Issue by yulng** [DaoCloud/network-charts-repackage#268]
https://github.com/DaoCloud/network-charts-repackage/tree/main/charts/nmstate/nmstate
实际是起来一个组件
![企业微信截图_82699283-4b93-485c-9bac-8abbb94b5f57](https://user-images.githubusercontent.com/31728060/203710094-a867b83e-9a2c-4970-91ff-49e84fd44969.png)
但文档中是三个组件
![企业微信截图_2ea8eb94-e06c-4e4c-8a39-ece08fc22108](https://user-images.githubusercontent.com/31728060/203710127-50423baa-e2e9-4a2b-9e2a-50263f617613.png)
【环境】10.6.158.63 calico环境（cilium环境周二也有相同现象）
https://demo-dev.daocloud.io/kpanda/clusters/nmstate/overview
需要说明启了很多个组件
![企业微信截图_93dcd738-0445-45cd-a34e-68fc0d41ee41](https://user-images.githubusercontent.com/31728060/203718595-4576e5d9-a294-4d0b-9b2a-00198d246aaa.png)

**Comment by yulng** [comment]
https://github.com/DaoCloud/network-charts-repackage/tree/main/charts/nmstate/nmstate

**Comment by yulng** [comment]
已修改

**Comment by cyclinder** [comment]
fixed by https://github.com/DaoCloud/network-charts-repackage/pull/273
