### ISSUE TITLE
there is overlay_interface field for veth plugin ?

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/network-charts-repackage#275]
https://github.com/DaoCloud/network-charts-repackage/blob/main/charts/multus-underlay/multus-underlay/templates/net-atta-def.yaml#L73
there is overlay_interface field for veth plugin ?

**Comment by cyclinder** [comment]
No, it's typo here.

**Comment by cyclinder** [comment]
fixed by https://github.com/DaoCloud/network-charts-repackage/pull/287
