### ISSUE TITLE
metallb安装时填写IP段，无法安装成功

### ISSUE THREAD

**Issue by yulng** [DaoCloud/network-charts-repackage#318]
【环境】10.6.158.63
https://demo-dev.daocloud.io/kpanda/clusters/nmstate/helm/charts/addon/metallb/install?version=0.13.7
【步骤】
1 HELM安装0.13.7版本
2 输入
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/31728060/207215491-973fda48-c49b-4c1b-b735-93f848a17f43.png">
3 POD没有起来
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/31728060/207215692-75087231-9248-4819-a18a-be8500ae151f.png">
4 使用CIDR输入没有问题

**Comment by cyclinder** [comment]
https://github.com/DaoCloud/network-charts-repackage/pull/319

**Comment by cyclinder** [comment]
跟 cidr 无关， interfaces 字段引入的bug，只要填写了 interface，就没问题，已在 https://github.com/DaoCloud/network-charts-repackage/pull/319 修复
