### ISSUE TITLE
metallb安装界面无法更新NodeSelectors和Interfaces等字段

### ISSUE THREAD

**Issue by yulng** [DaoCloud/network-charts-repackage#331]
metallb安装界面无法更新NodeSelectors和Interfaces等字段
1安装运行好metallb
2 从界面helm应用更新字段，报如图
<img width="1357" alt="企业微信截图_fcfc8611-8456-4f4c-b78c-1f7efc95f001" src="https://user-images.githubusercontent.com/31728060/208399907-6e06526f-1f2b-42db-89f0-62377928b4dd.png">

**Comment by cyclinder** [comment]
helm 本身不支持 更新 CR 资源，如果要更新请直接更新 CR
